version: '3'
services:
  demo_mysql:
    container_name: demo-mysql
    image: mysql/mysql-server
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: pfhKqNoLkHcnbbDVFS3b1Rs30/z2qyGQZkdNNrvc/Ks=
      MYSQL_ROOT_HOST: '%'
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    networks:
      - demo

  app:
    build:
      context: ./server
    container_name: demo-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: mysql
      DATABASE_HOST: demo_mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: demo
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: pfhKqNoLkHcnbbDVFS3b1Rs30/z2qyGQZkdNNrvc/Ks=
      APP_KEYS: qxwVqIofPsopfiJl5Wu9sw==,koovyzzi8Z12daIxeRLgcA==,PWxsX1TcoFUSfCgFLioP9Q==,0FPedZkTkTiCc00k2S3fVg==
      JWT_SECRET: /8N2NSSt4geB8wDWZoZ8AQ==
      ADMIN_JWT_SECRET: ElC2n+u1jXARUmT3dt7dtA==
      API_TOKEN_SALT: gOpkyn5ZF2s7gGVNvwu8Ow==
    volumes:
      - ./app:/srv/app
    ports:
      - 127.0.0.1:8000:1338
    depends_on:
      - demo_mysql
    networks:
      - demo
networks:
  demo: